### ISSUE TITLE
community solutions: retrieve other solutions by the same author

### ISSUE THREAD

**Issue by hilary** [exercism/exercism#4206]
In v1, if I recall correctly, when looking at the equivalent of community solutions, I could then select the author and navigate (somehow) to other solutions by the same author.

In v2, I can't do anything with the author info on a community solution page. It doesn't link to the author profile, etc.

Please link the author info on community solutions to the author's profile so we can navigate by author.

**Comment by iHiD** [comment]
Author information should appear if the person has created a profile and
doesn't if they haven't (as there's no page to link to in V2). Are you
seeing missing links when people have profiles?

**Comment by hilary** [comment]
I am indeed. Here's one of mine (I have a v2 profile):

https://exercism.io/tracks/go/exercises/secret-handshake/solutions/df5e7d2a36584b45856eaff845bb2876

and one of sebito91's (he has a v2 profile):

https://exercism.io/tracks/go/exercises/space-age/solutions/8924743bf0f2444c88759c5ca143aeb8

Those were both published before the switch to v2, so here's one that I published since switching to v2:

https://exercism.io/tracks/go/exercises/series/solutions/f79c0c62f52547e49b83e92496bbf167

Since it isn't possible to sort the community solutions, there's really no way to get to someone's solutions other than to figure out what their profile url is, type it in, and navigate that way... Doable but sub-optimal.

**Comment by sshine** [comment]
I can confirm that there still isn't a link to the author's profile in the community solution page. Unless the author submits a comment to their solution, in which case their name above the comment will be such a link to the author's profile.

**Comment by ErikSchierboom** [comment]
Hello 👋

With the launch of Exercism v3, we are **closing all issues in this repository** to help give us a clean slate to detect new problems. If this issue is still relevant to Exercism v3 (e.g. it's a feature that we haven't implemented in v3, or a bug that still exists), please reopen it and we will review it and post an update on it as soon as we get chance.

Thanks for helping make Exercism better, and we hope you enjoy v3 🙂
