### ISSUE TITLE
Isogram in the elm track seems to be broken

### ISSUE THREAD

**Issue by syeo66** [exercism/exercism#4993]
I was able to download it by removing the whole uuid part from 
`exercism download --exercise=isogram-ed04a8a4-05aa-4289-bdf0-33a4cd6ca36d --track=elm`

but then my uploaded solution was not recognized after submitting (as was to be expected, I guess).

**Comment by iHiD** [comment]
Thank you. This should be fixed by https://github.com/exercism/elm/pull/259/files

**Comment by syeo66** [comment]
Thanks, this made Isometric available. However with a small odd artifact.
![Bildschirmfoto 2019-08-22 um 20 09 54](https://user-images.githubusercontent.com/1178021/63538841-04fc2b00-c519-11e9-9fa5-c3c2c1ca8466.png)

**Comment by iHiD** [comment]
@syeo66 Is that still there for you?

**Comment by syeo66** [comment]
@iHiD Yes, still the same. The link goes to https://exercism.io/my/solutions/d751b2dec939465daffd6e39d512b90b

**Comment by iHiD** [comment]
Interesting. Thanks.
