### ISSUE TITLE
Published solution is not published

### ISSUE THREAD

**Issue by bobahop** [exercism/exercism#6210]
My "Secret Handshake" for C is published, but it does not show up in the community solutions

![info_1](https://user-images.githubusercontent.com/32035397/151671845-018f15a2-d619-4e6d-8858-0cbe628ae916.JPG)
![info_2](https://user-images.githubusercontent.com/32035397/151671853-fa5b3bfe-b920-4d3f-bd41-77ea3c3237de.JPG)
.

**Comment by limaxophobiac** [comment]
I have the same issue with 'Zipper' over in the Javascript track. I've published it but it doesn't show up in community solutions or under profiles/limaxophobiac/solutions or journey/reputation.

**Comment by gacallea** [comment]
hi :)

the same happened to me with https://exercism.org/tracks/elm/exercises/isogram

I solved it and published it a couple of days ago, when Exercism "managed to DoS themselves" (their words on Twitter). it is not showing in my profile nor community solutions. Even if I received the notification/+1 "karma".

I tried slightly changing my iteration by adding a comment but still no luck. please help :)

**Comment by iHiD** [comment]
@ErikSchierboom Do we potentially have some issues with Cloudsearch updating? Could you check these three examples pls?

**Comment by colincullen** [comment]
Same here on the Elixir track
